[build]
builder = "NIXPACKS"
buildCommand = "pnpm install && pnpm turbo build --filter=@playground/web"

[deploy]
startCommand = "node apps/web/.next/standalone/apps/web/server.js"
healthcheckPath = "/"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
